### ISSUE TITLE
Kernel modules

### ISSUE THREAD

**Issue by Liberasys** [gemian/gemian#1]
Hello, and thank you for the fantastic work on gemini and cosmo.
I own a cosmo and I wanted to do a raw backup of /dev/mmcblk0 before playing with it...
But it seems to have no NFS or samba kernel module... Thus I cannot stream my backup to my NAS.
Is there a way to compile myself a module ? Could some modules be added to default kernel in your disto ?

**Comment by adamboardman** [comment]
The config file is: [k71v1_64_bsp_defconfig](https://github.com/gemian/cosmo-linux-kernel-4.4/blob/master/arch/arm64/configs/k71v1_64_bsp_defconfig)
Self built kernels appear to be a work in progress, last time I tried the WiFi didn't work, running 'debuild -b -uc -us' from the 'packaging' branch of the kernel on a debian 10 desktop (or lxc container) should give you a .deb you can install on the device. One of my next todo's is probably to bug Nikita/Davide to see where we are at with the kernel, for example Nikita has been putting some interesting changes into the ubports branch recently.
Currently the 'native' branch should be buildable on the Cosmo device but due to a missing kernel module it fails in a final step where it would need qemu support, though it works on the build server from this branch as its using qemu for the arm64 support.

**Comment by adamboardman** [comment]
I've added the needed [modules](https://github.com/gemian/cosmo-linux-kernel-4.4/commit/70f0dc0f3a0a67ca1b678b386b1cfacee72e5b4f) as requested. I've also removed the [multi-branch](https://github.com/gemian/cosmo-linux-kernel-4.4/commit/fc4253769f854b888b5515b1d316593dbc3d3df9) needs so that now the 'packaging' branch can be built both on device and cross compiled so the 'native' branch is now orphaned, also binfmt for qemu support so once you have a new enough kernel you can self build new kernels on the device.
