### ISSUE TITLE
Gemini upgrading from stretch to buster repo: lxc-android needs cosmo-linux-kernel

### ISSUE THREAD

**Issue by drhpc** [gemian/gemian#27]
I just upgraded my Gemini from stretch to buster (no reboot yet, just apt upgrade). There is one packaging issue:

gemian-desktop-minimal needs lxc-android which needs cosmo-linux-kernel

How can that be avoided? A different desktop package for Gemini? A different lxc package? A soft dependency? Personally, I guess I do not need the lxc stuff as I want a bare Debian Linux experience, but it is there for a reason, I presume.

**Comment by adamboardman** [comment]
In the bookworm land I've updated kernel building to use [planet-linux-kernel](https://github.com/gemian/astro-linux-kernel-4.14/blob/packaging/debian/control#L22) as a generic name for things like lxc-android to then depend upon. Unfortunately existing builds have all been done with single device being targetted for each debian version. I'd recommend waiting for me to get round to bookworm on gemini for an upgrade.

If you want any kind of graphics you need gemian-system, lxc-android as we https://github.com/gemian/gemian/wiki/UpdateAndroidSystemLXCImage - basically your running a mini-android in an LXC container to talk to the hardware via the hybris stuff.

I've only left breadcrumbs of how I'm thinking of porting things backwards, never done any image building or testing on older devices. The suggested upgrade path would be to install a fresh image for each device rather than dist-upgrade.... this will be better in the future with the LVM support so that you can keep the old one there and resize them etc.
